### ISSUE TITLE
BMP Peer Flags registries

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/rfc9069-AUTH48#6]
Does the following text refer to the "BMP Peer Flags for 
Peer Types 0 through 2" or "BMP Peer Flags for Loc-RIB Instance Peer Type 3" registry?  In "BMP     
Peer Flags for Loc-RIB Instance Peer Type 3", Flag 0 has been registered as F flag.  In "BMP Peer   
Flags for Peer Types 0 through 2", values 0-3 were assigned in other RFCs, so they're not           
"unassigned".

See the "BGP Monitoring Protocol (BMP) Parameters" registry
<https://www.iana.org/assignments/bmp-parameters>.

Original:
   Flags 0 through 3 and 5 through 7 are unassigned.  The registration
   procedure for the registry is "Standards Action".

**Comment by paololucente** [comment]
> In "BMP Peer Flags for Loc-RIB Instance Peer Type 3", Flag 0 has been registered as F flag

The F flag issue was handled as part of Issue #7 . Do we agree this is resolved?

> In "BMP Peer Flags for Peer Types 0 through 2", values 0-3 were assigned in other RFCs, so they're not "unassigned".

Previously in that same section it says `This document defines that peer flags are specific to the Loc-RIB instance peer type.` So the context for this sentence is "BMP Peer Flags for Loc-RIB Instance Peer Type 3". Do you believe this does require a further clarification?

**Comment by TimEvens** [comment]
This was left over when we were still using flag 4.   I will resolve this via a PR.

**Comment by TimEvens** [comment]
This is a good change.  I never really liked giving instructions to IANA in the draft when they have been done by the time the draft has been pushed.  The changes @sginoza provides changes it from actions to be done to actions that have been done based on this RFC.  IMHO, I like this better and it reads better of "*what was done*" instead of "*what needs to still be done*." I believe it's fine to define what needs to be done in draft, but when it is an RFC published document it is more clear to indicate what has been done as the result of the RFC to IANA.   

One addition correction.... 

> FROM:

```
   Flags 0 through 3 and 5 through 7 are unassigned.  The registration
   procedure for the registry is "Standards Action".
```

> TO:

```
   Flags 1 through 7 are unassigned.  The registration procedure for the
   registry is Standards Action.
```

I'll include this update in the PR.
